# POST http://localhost:3000/create-enrichment
# Content-Type: application/json

# {
#     "name": "Selenium's Enrichment",
#     "repeats": false,
#     "hostName": "Selenium",
#     "roomName": "107-LIB",
#     "singleDay": "10/7/2022"
# }

# POST http://localhost:3000/register
# Content-Type: application/json

# {
#     "username": "Skylarenium4",
#     "password": "LeDiamondMob01"
# }

# POST http://localhost:3000/login
# Content-Type: application/json

# {
#     "username": "Skylarenium4",
#     "password": "LeDiamondMob01"
# }

# PATCH http://localhost:3000/register-enrichment
# Content-Type: application/json

# {
#     "user": {
#         "username": "Skylarenium4",
#         "password": "LeDiamondMob01"
#     },
#     "date": "02/13/2023",
#     "enrichmentName": "Ritvik's Fun Place"
# }

# GET http://localhost:3000/get-enrichments
# Content-Type: application/json

# {
#     "user": {
#         "username": "Skylarenium3",
#         "password": "LeDiamondMob01"
#     }
# }

# POST http://localhost:3000/retrieve
# Content-Type: application/json

# {

# }